#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0
echo "$FILES" | xargs yarn format:fix
echo "$FILES" | xargs git add
node tools/scripts/update-pnpm-lock-if-needed.cjs || exit 1
node tools/scripts/check-hardcoded-colors.cjs --staged

exit 0
